class ChessModel(nn.Module):
    def __init__(self):
        super(ChessModel, self).__init__()
        self.linear1 = nn.Linear(12 * 8 * 8 + 4 + 8 + 1, 512)
        self.bn1 = nn.BatchNorm1d(512)
        self.linear2 = nn.Linear(512, 1024)
        self.bn2 = nn.BatchNorm1d(1024)
        self.linear3 = nn.Linear(1024, 2048)
        self.bn3 = nn.BatchNorm1d(2048)
        self.dropout1 = nn.Dropout(0.2)
        self.linear4 = nn.Linear(2048, 1024)
        self.bn4 = nn.BatchNorm1d(1024)
        self.dropout2 = nn.Dropout(0.2)
        self.linear5 = nn.Linear(1024, 512)
        self.bn5 = nn.BatchNorm1d(512)
        self.dropout3 = nn.Dropout(0.2)
        self.linear6 = nn.Linear(512, 256)
        self.bn6 = nn.BatchNorm1d(256)
        self.dropout4 = nn.Dropout(0.2)
        self.linear7 = nn.Linear(256, 64)
        self.bn7 = nn.BatchNorm1d(64)
        self.dropout5 = nn.Dropout(0.2)
        self.linear8 = nn.Linear(64, 1)
        
    def forward(self, x):
        x = torch.relu(self.bn1(self.linear1(x)))
        x = torch.relu(self.bn2(self.linear2(x)))
        x = torch.relu(self.bn3(self.linear3(x)))
        x = self.dropout1(x)
        x = torch.relu(self.bn4(self.linear4(x)))
        x = self.dropout2(x)
        x = torch.relu(self.bn5(self.linear5(x)))
        x = self.dropout3(x)
        x = torch.relu(self.bn6(self.linear6(x)))
        x = self.dropout4(x)
        x = torch.relu(self.bn7(self.linear7(x)))
        x = self.dropout5(x)
        x = self.linear8(x)
        # Clamp the output to -50 and 50
        x = torch.clamp(x, -50, 50)
        return x